data-otrs:
  command: /bin/true
  image: juanluisbaptiste/otrs:latest
mariadb:
  environment:
    MYSQL_ROOT_PASSWORD: changeme
  expose:
  - '3306'
  image: juanluisbaptiste/otrs-mariadb:latest
otrs:
  environment:
    MYSQL_ROOT_PASSWORD: changeme
    OTRS_ADMIN_EMAIL: admin@yourcompany.com
    OTRS_DB_PASSWORD: changeme
    OTRS_HOSTNAME: support.yourcompany.com
    OTRS_POSTMASTER_FETCH_TIME: 0
    OTRS_ROOT_PASSWORD: changeme
  image: juanluisbaptiste/otrs:latest
  links:
  - mariadb:mariadb
  - postfix:postfix
  ports:
  - 80:80

postfix:
  environment:
    SERVER_HOSTNAME: test
    SMTP_PASSWORD: test
    SMTP_SERVER: test.test.it
    SMTP_USERNAME: test
  expose:
  - '25'
  image: juanluisbaptiste/postfix:latest
